# Generated by Django 5.1.4 on 2024-12-07 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_address', models.CharField(max_length=100)),
                ('branch_ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('shift_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_employees', to='webapp.branch')),
                ('emp_shift', models.ManyToManyField(blank=True, related_name='shift_employees', to='webapp.shift')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='associated_branches', to='webapp.employee'),
        ),
    ]
