# Generated by Django 5.1.4 on 2024-12-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_shift_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='employees',
        ),
    ]
