# Generated by Django 5.1.4 on 2024-12-23 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_branch_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='shift',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_branch',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_name',
            new_name='emp_Fname',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='shift_end',
            new_name='shift_expected_time_in',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='shift_start',
            new_name='shift_expected_time_out',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_email',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_Lname',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_Mname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_comp_id',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], default=str, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_department',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, related_name='department_employees', to='webapp.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_department',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, related_name='department_shifts', to='webapp.department'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
