# Generated by Django 5.1.4 on 2024-12-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_department_remove_shift_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_role',
            field=models.CharField(choices=[('Regular Employee', 'Regular Employee'), ('Department Head', 'Department Head')], default=str, max_length=20),
            preserve_default=False,
        ),
    ]
