# Generated by Django 5.1.4 on 2024-12-23 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_employee_emp_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_date_hired',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_leave_credits',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
    ]
