# Generated by Django 5.1.4 on 2024-12-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_contact_no',
            field=models.CharField(default=str, max_length=20),
            preserve_default=False,
        ),
    ]
